project_id = "upfhnofgkuafejuvxkrr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
port = 54325

[realtime]
enabled = true

[edge-functions]
[edge-functions.send-welcome-email]
verify-jwt = true

[edge-functions.handle-new-user]
verify-jwt = true