// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upfhnofgkuafejuvxkrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwZmhub2Zna3VhZmVqdXZ4a3JyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwNTEwNDgsImV4cCI6MjA1MTYyNzA0OH0.ucM-tl2zj1OZU_T0cohR1EY_UzlNwuMER_PifS28Glk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);